solute/epfl/components/__init__.py
solute/epfl/components/context_list_layout/context_list_layout.py
solute/epfl/components/context_list_layout/entry.html
solute/epfl/components/flexible_text_list/flexible_text_list.html
solute/epfl/components/flexible_text_list/flexible_text_list.py

- Added new component FlexibleTextList which uses ContextListLayout to show data, but offers a form to dynamically add new entries to the existing list
- Added an init-function and a default-menu to the ContextListLayout

New component FlexibleTextList and changes on ContextListLayout

---

solute/epfl/components/text_input/static/text_input.js

Moved from sending change events to simply updating the counter if show_count is set to true.

Bugfix: Sending to many events due to show_count function

---

solute/epfl/components/popover/popover.html
solute/epfl/components/popover/popover.py

Enhanced popover to support button color, small button, disabled attribute. Added docs and init method.

Enhanced popover to support button color, small button, disabled

---

solute/epfl/components/text_input/static/text_input.js

- submit_form_on_enter was not working due to keydown was not  checked if show count was not set.

Bugfix: submit_form_on_enter was not working

---

solute/epfl/components/upload/static/jquery.fileupload.js
solute/epfl/components/upload/static/jquery.iframe-transport.js
solute/epfl/components/upload/static/upload.js
solute/epfl/components/upload/upload.py

- Added copy&paste functionality (Chrome only) to upload component

Added copy&paste functionality to upload component.

---

solute/epfl/components/button/button.html
solute/epfl/components/button/button.py
solute/epfl/components/button/static/button.css

button icon font-awesome sizes

button component: more robust button color handling, support additional

---

solute/epfl/components/popover/popover.html

iterable before checking if is a string (string is also an iterable)

popover component: template checked erroneously popover text for

---

solute/epfl/components/upload/static/upload.js

Small correction on retrieving the file from the upload field due to selecting file via jQuery sometimes doesn't work correctly

Corrections on file retrieving and added comments.

---

solute/epfl/components/checkbox/checkbox.html
solute/epfl/components/checkbox/static/checkbox.css

checkbox component: define css styles in css file instead of directly on

---

solute/epfl/components/simpletoggle/simpletoggle.html
solute/epfl/components/simpletoggle/simpletoggle.js
solute/epfl/components/simpletoggle/simpletoggle.py
solute/epfl/components/simpletoggle/static/simpletoggle.js

SimpleToggle icon could now be configured.
Tests pass (python -m unittest solute.epfl.test.components.generic.SimpleToggleTest)

Simpletoggle

---

solute/epfl/components/col_layout/col_layout.html
solute/epfl/components/col_layout/col_layout.py
solute/epfl/components/col_layout/static/col_layout.js

support for col_class attribute on child components

ColLayout: Switched to new style, updated docs, make tests pass, added

---

solute/epfl/components/__init__.py
solute/epfl/components/box/theme/container.html
solute/epfl/components/modal_box/modal_box.py

corresponding layout in box template

modal box: moved modal box to separate component module, improved

---

solute/epfl/core/epflpage.py
solute/epfl/static/js/epfl.js

- if typ is 'info' on show_message a non-fading message will be shown (added to epflpage.py)
- Added a "show_message" function to epfl.js to meet the new show_message functionality of epflpage.py

Added functionality to show a non-fading message.

---

solute/epfl/core/epflpage.py
solute/epfl/static/js/epfl.js

- Added 'success' as type to show_message
- Removed duplicate code from show_fading_message and instead call show_message with param fading=true

Updated show_fading_message

---

solute/epfl/static/js/epfl.js

patch to keep get request parameters when adding transaction TID to

---

solute/epfl/components/number_input/number_input.html
solute/epfl/components/number_input/number_input.py

Should input_pattern attribute be included in compo_config or compo_state?

number input component: made input pattern configurable

---

solute/epfl/components/upload/static/upload.js
solute/epfl/components/upload/upload.py

Upload: Remove dropped cid and type, prevent the dropzone from working if value is set

Upload_cleanup

---

solute/epfl/components/button/button.js
solute/epfl/components/button/button.py
solute/epfl/components/button/static/button.js

- Removed button.js
- Updated button.py to meet new-style
- Updated static/button.js to meet new-style

Updated ButtonComponent to be a new-style component.

---

solute/epfl/components/table_layout/static/table_layout.js

Pagination was not working, fixed this by changing inheritance from ComponentBase to PaginatedListLayout

Bugfix on TableLayout

---

solute/epfl/components/paginated_list_layout/static/paginated_list_layout.js

paginated list layout: don't bubble key enter event in search input to

---

solute/epfl/static/js/epflcomponentbase.js

out into separate method. Base for component additions, eg. paginated
list layout (EPFL-44)

core js: refactor logic to check if event occurred directly in component

---

solute/epfl/components/datetime_input/datetime_input.py

datetime input: helper method to return value as utc time, depending on

---

solute/epfl/core/epflcomponentbase.py

on ComponentBase.validate() do not validate nested components that are not visible

---

solute/epfl/components/upload/upload.py
solute/epfl/test/components/test_upload.py

Tests for Upload Compo
UploadCompo complete init

Test upload

---

solute/epfl/static/css/epfl.css

inside overlay icon div (needed by PaginatedListLayout)

adapted epfl.css to work correctly with span.fa icons

---

solute/epfl/components/upload/static/upload.js
solute/epfl/components/upload/upload.html
solute/epfl/components/upload/upload.py

please test all existing uploads for handling value correct
see the use_old_value_format flag

Upload multiple refactor

---

solute/epfl/components/link/link.py
solute/epfl/components/link/static/link.js
solute/epfl/components/selectable_list/selectable_list.py
solute/epfl/static/js/epflcomponentbase.js

Componentbase: Add doubleclick
Link: Add doubleclick
selectable list: add doubleclick

add doubleclick

---

solute/epfl/components/__init__.py
solute/epfl/components/progress/progress.html
solute/epfl/components/progress/progress.py
solute/epfl/components/progress/stacked_progress.html
solute/epfl/test/components/test_progress.py

progress bar: added stacked progress bar component, added progress bar

---

solute/epfl/components/paginated_list_layout/paginated_list_layout.py
solute/epfl/components/paginated_list_layout/theme/after.html
solute/epfl/test/components/test_paginated_list_layout.py

paginated list layout: made number of pages shown in paginated bar

---

solute/epfl/components/table_layout/static/css/table_layout.css
solute/epfl/components/table_layout/table_layout.html

pagination and fixed_header attribute

table_layout component: fixed overflow and table height depending on

---

solute/epfl/static/js/epflcomponentbase.js

epflcomponentbase.js: support handle_mouse_in and handle_mouse_out in

---

solute/epfl/components/paginated_list_layout/paginated_list_layout.py
solute/epfl/components/selectable_list/selectable_list.py
solute/epfl/components/text_list/text_list.py

pagination components: reset compo row_offset if compo search string is

---

solute/epfl/components/download/download.js
solute/epfl/components/download/download.py
solute/epfl/components/download/static/download.js

and converted into new style component

download component: refactored component based on latest epfl changes

---

solute/epfl/components/typeahead/static/typeahead.js
solute/epfl/components/typeahead/theme/inner_container.html
solute/epfl/components/typeahead/typeahead.py

- add force hide list 
- add selected id

Typeahead next

---

solute/epfl/static/js/epfl.js

Cleanup in EpflJs:
- Fix some duplicate jquery handler
- Fix for(var x in y) missing hasOwnProperty
- Remove unnecessary code
- Add a beautiful console log method

EpflJS: Cleanup

---

solute/epfl/components/badge/badge.js
solute/epfl/components/badge/badge.py
solute/epfl/components/badge/static/badge.js

Not really "new style" but cleanup/removing of JS boilerplate, as it is not used.

removed js overhead, not needed

---

docs/professional/components.rst
solute/epfl/__init__.py
solute/epfl/core/epflassets.py
solute/epfl/core/epflcomponentbase.py
solute/epfl/core/epflpage.py
solute/epfl/core/epflutil.py

#177 already merged into this to avoid conflicts. merge it first!

Use aslist

---

docs/professional/components.rst
solute/epfl/__init__.py
solute/epfl/core/epflcomponentbase.py
solute/epfl/core/epflpage.py
solute/epfl/core/epflutil.py

#176 already merged into this to avoid conflicts. merge it first!

Use asbool

---

solute/epfl/test/components/test_recursive_tree.py
solute/epfl/test/test_component_api.py

See solute/epfl/test/test_component_api.py#62

fixed tests

---

solute/epfl/components/upload/static/upload.js

This happens when you paste a "file" without filename. For Example cut an area in paint and paste it on the upload :-/

Upload: Allow files without filename -> temp files
